# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{righttp}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["hukl"]
  s.date = %q{2010-08-15}
  s.description = %q{A HTTP client library written from scratch that is easy to use and offers full flexibility}
  s.email = %q{contact@smyck.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "doc/mission.textile",
     "lib/rig/http.rb",
     "lib/rig/http_body.rb",
     "lib/rig/http_exceptions.rb",
     "lib/rig/http_header.rb",
     "lib/rig/http_response.rb",
     "lib/righttp.rb",
     "righttp.gemspec",
     "test/fixtures/yay.gif",
     "test/helper.rb",
     "test/test_http.rb"
  ]
  s.homepage = %q{http://github.com/hukl/righttp}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A HTTP client library from scratch for ruby1.9}
  s.test_files = [
    "test/helper.rb",
     "test/test_http.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

